services:
  rd-course-starter-api:
    image: rd-course-starter-api
    container_name: rd-course-starter-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: pnpm run start:dev
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres
    container_name: local_pgdb
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql

volumes:
  local_pgdata:
